# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiForPairing.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_srcM = QtWidgets.QPushButton(self.centralwidget)
        self.b_srcM.setGeometry(QtCore.QRect(170, 10, 611, 41))
        self.b_srcM.setObjectName("b_srcM")
        self.b_srcW = QtWidgets.QPushButton(self.centralwidget)
        self.b_srcW.setGeometry(QtCore.QRect(170, 50, 741, 41))
        self.b_srcW.setObjectName("b_srcW")
        self.b_fld = QtWidgets.QPushButton(self.centralwidget)
        self.b_fld.setGeometry(QtCore.QRect(170, 90, 741, 40))
        self.b_fld.setObjectName("b_fld")
        self.b_start_and_done = QtWidgets.QPushButton(self.centralwidget)
        self.b_start_and_done.setGeometry(QtCore.QRect(10, 140, 901, 23))
        self.b_start_and_done.setObjectName("b_start_and_done")
        self.lb_srcM = QtWidgets.QLabel(self.centralwidget)
        self.lb_srcM.setGeometry(QtCore.QRect(10, 10, 160, 31))
        self.lb_srcM.setObjectName("lb_srcM")
        self.lb_srcW = QtWidgets.QLabel(self.centralwidget)
        self.lb_srcW.setGeometry(QtCore.QRect(10, 50, 160, 31))
        self.lb_srcW.setObjectName("lb_srcW")
        self.lb_fld = QtWidgets.QLabel(self.centralwidget)
        self.lb_fld.setGeometry(QtCore.QRect(10, 90, 160, 31))
        self.lb_fld.setObjectName("lb_fld")
        self.b_chekMEK = QtWidgets.QPushButton(self.centralwidget)
        self.b_chekMEK.setGeometry(QtCore.QRect(780, 10, 131, 41))
        self.b_chekMEK.setObjectName("b_chekMEK")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 21))
        self.menubar.setObjectName("menubar")
        self.menumain = QtWidgets.QMenu(self.menubar)
        self.menumain.setObjectName("menumain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menumain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_srcM.setText(_translate("MainWindow", "Выбор Ката"))
        self.b_srcW.setText(_translate("MainWindow", "Выбор Лога"))
        self.b_fld.setText(_translate("MainWindow", "Кудыть"))
        self.b_start_and_done.setText(_translate("MainWindow", "Запустить компоновку квитанций"))
        self.lb_srcM.setText(_translate("MainWindow", "путь до мэк"))
        self.lb_srcW.setText(_translate("MainWindow", "путь до водотеплухи"))
        self.lb_fld.setText(_translate("MainWindow", "путь до результатом доволен"))
        self.b_chekMEK.setText(_translate("MainWindow", "чекМЭК(Отчёт№1)"))
        self.menumain.setTitle(_translate("MainWindow", "main"))
