# 1
__all__ = [
    "Track",
    "tracks",
]
from collections import defaultdict
from enum import Enum

# interface:
Track = Enum("Track", nms := ["Unknown", "Непечатное", "Левицкой", "IT"])
for i in range(len(Track)):
    locals()[nms[i]] = Track(i + 1)
    __all__.append(nms[i])

tracks = defaultdict(lambda: (-1, Unknown))
# autogenerated below:
